# Generated by Django 5.2 on 2026-06-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_crisisreport_nature_of_crisis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crisisreport',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='lon',
        ),
    ]
