# Generated by Django 5.2 on 2026-06-11 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_lat_lon_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCrisisReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField(blank=True, null=True)),
                ('original_report_id', models.UUIDField(blank=True, help_text='Reference to source CrisisReport', null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('building_footprint_id', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('infrastructure_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('government', 'Government'), ('utility', 'Utility'), ('transport', 'Transport & Communication'), ('community', 'Community'), ('recreation', 'Public Recreation'), ('other', 'Other')], max_length=50, null=True)),
                ('nature_of_crisis', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('tsunami', 'Tsunami'), ('cyclone', 'Cyclone/Hurricane'), ('wildfire', 'Wildfire'), ('explosion', 'Explosion'), ('conflict', 'Conflict'), ('civil_unrest', 'Civil Unrest'), ('chemical', 'Chemical Incident'), ('other', 'Other')], max_length=50, null=True)),
                ('debris', models.BooleanField(default=False)),
                ('affected_units', models.PositiveIntegerField(blank=True, null=True)),
                ('damage_level', models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('partial', 'Partial'), ('complete', 'Complete')], max_length=20, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('ai_damage_level', models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('partial', 'Partial'), ('complete', 'Complete')], max_length=32, null=True)),
                ('ai_disaster_type', models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('fire', 'Fire'), ('flood', 'Flood'), ('hurricane', 'Hurricane'), ('landslide', 'Landslide'), ('not_disaster', 'Not disaster'), ('other_disaster', 'Other')], max_length=32, null=True)),
                ('ai_informativeness', models.CharField(blank=True, choices=[('informative', 'Informative'), ('not_informative', 'Not informative')], max_length=32, null=True)),
                ('ai_humanitarian_category', models.CharField(blank=True, choices=[('affected_injured_or_dead_people', 'Affected/injured/dead people'), ('infrastructure_and_utility_damage', 'Infrastructure and utility damage'), ('not_humanitarian', 'Not humanitarian'), ('rescue_volunteering_or_donation_effort', 'Rescue/volunteering/donation effort')], max_length=64, null=True)),
                ('ai_damage_severity', models.CharField(blank=True, choices=[('little_or_no_damage', 'Little or no damage'), ('mild_damage', 'Mild damage'), ('severe_damage', 'Severe damage')], max_length=32, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['building_footprint_id'], name='api_finalcr_buildin_dc0644_idx'), models.Index(fields=['infrastructure_type'], name='api_finalcr_infrast_b73439_idx'), models.Index(fields=['ai_disaster_type'], name='api_finalcr_ai_disa_5410c3_idx'), models.Index(fields=['-submitted_at'], name='api_finalcr_submitt_effa29_idx')],
            },
        ),
    ]
