# Generated by Django 5.2 on 2026-06-15 20:07 (hand-edited for jsonb → geometry cast)

import django.contrib.gis.db.models.fields
from django.db import migrations

_TO_GEOMETRY = (
    "ALTER TABLE {table} "
    "ALTER COLUMN location TYPE geometry(POINT, 4326) "
    "USING CASE "
    "  WHEN location IS NULL THEN NULL "
    "  WHEN jsonb_typeof(location) = 'string' "
    "    THEN ST_SetSRID(ST_GeomFromGeoJSON(location #>> '{{}}'), 4326) "
    "  ELSE ST_SetSRID(ST_GeomFromGeoJSON(location::text), 4326) "
    "END;"
)

_TO_JSONB = (
    "ALTER TABLE {table} "
    "ALTER COLUMN location TYPE jsonb "
    "USING CASE WHEN location IS NULL THEN NULL "
    "ELSE ST_AsGeoJSON(location)::jsonb END;"
)

TABLES = ['api_crisisreport', 'api_finalcrisisreport', 'api_responder']


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_responder_location'),
    ]

    operations = [
        migrations.RunSQL(
            sql=["CREATE EXTENSION IF NOT EXISTS postgis;"]
                + [_TO_GEOMETRY.format(table=t) for t in TABLES],
            reverse_sql=[_TO_JSONB.format(table=t) for t in TABLES],
            state_operations=[
                migrations.AlterField(
                    model_name='crisisreport',
                    name='location',
                    field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
                ),
                migrations.AlterField(
                    model_name='finalcrisisreport',
                    name='location',
                    field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
                ),
                migrations.AlterField(
                    model_name='responder',
                    name='location',
                    field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
                ),
            ],
        ),
    ]
