# Generated by Django 5.2 on 2026-06-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_final_crisis_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='location',
            field=models.JSONField(blank=True, help_text='Current location as GeoJSON Point', null=True),
        ),
        migrations.AddField(
            model_name='responder',
            name='location_description',
            field=models.TextField(blank=True, help_text='Human-readable location description', null=True),
        ),
    ]
