# Generated by Django 5.2 on 2026-06-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fix_location_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisreport',
            name='location_description',
            field=models.TextField(blank=True, help_text="Natural language place description, e.g. 'Near the central market' or 'Beside the collapsed school building'", null=True),
        ),
        migrations.AlterField(
            model_name='finalcrisisreport',
            name='location_description',
            field=models.TextField(blank=True, help_text="Landmark-based description of the affected site, e.g. 'Behind the old railway station' or 'Ground floor of the red brick building'", null=True),
        ),
        migrations.AlterField(
            model_name='finalcrisisreport',
            name='original_report_id',
            field=models.UUIDField(blank=True, help_text='Reference to source CrisisReport', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='responder',
            name='location_description',
            field=models.TextField(blank=True, help_text="Where the responder is currently deployed, e.g. 'Outside the main hospital gate' or 'At the northern checkpoint'", null=True),
        ),
    ]
