# Generated by Django 5.2 on 2026-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_unique_original_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisisreport',
            name='nature_of_crisis',
            field=models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('tsunami', 'Tsunami'), ('cyclone', 'Cyclone/Hurricane'), ('wildfire', 'Wildfire'), ('landslide', 'Landslide'), ('explosion', 'Explosion'), ('conflict', 'Conflict'), ('civil_unrest', 'Civil Unrest'), ('chemical', 'Chemical Incident'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalcrisisreport',
            name='nature_of_crisis',
            field=models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('tsunami', 'Tsunami'), ('cyclone', 'Cyclone/Hurricane'), ('wildfire', 'Wildfire'), ('landslide', 'Landslide'), ('explosion', 'Explosion'), ('conflict', 'Conflict'), ('civil_unrest', 'Civil Unrest'), ('chemical', 'Chemical Incident'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
